added server
htmlacademy-nodejs/587797-buy-and-sell-3 pull request #5
Opened 2020-01-30 15:39 UTC by Shv-sergey70

2020-01-30 16:09 UTC, rmuhamedgaliev requested changes
Ты молодец что при выполнении задания постарался сделать обработку ошибок и верно указал типы возвращаемых данных. Но посмотри комментарий по проверку наличия файла. [Б1]

2020-01-30 16:09 UTC, rmuhamedgaliev commented on src/service/cli/server.js
> +        const fileContent = await fs.readFile(MOCK_FILE_PATH);
Тут я бы тебя немного поправил, так как вариант почти рабочий. Вариант `try ... catch` отрабатывает, но если например возникает ошибка при парсинге файла, а не при чтении. У модуля **fs** есть функция проверки наличия файла [fs.stat(path[, options], callback)](https://nodejs.org/api/fs.html#fs_fs_stat_path_options_callback). Тогда проверка будет корректнее. А уже если произошла непредвиденная ошибка, то стоит использовать ошибку 500.

2020-01-31 08:37 UTC, Shv-sergey70 commented on src/service/cli/server.js
> +        const fileContent = await fs.readFile(MOCK_FILE_PATH);
> Using fs.stat() to check for the existence of a file before calling fs.open(), fs.readFile() or fs.writeFile() is not recommended. Instead, user code should open/read/write the file directly and handle the error raised if the file is not available.

2020-01-31 10:47 UTC, Shv-sergey70 commented on src/service/cli/server.js
> +        const fileContent = await fs.readFile(MOCK_FILE_PATH);
Сделал следующую логику:
Смотрю по коду ошибки, если это `ENOENT` - отправляю 404, иначе 500

2020-01-31 18:15 UTC, rmuhamedgaliev commented on src/service/cli/server.js
> +        const fileContent = await fs.readFile(MOCK_FILE_PATH);
Хорошее интересное решение. Можно так. Я хотел обратить твоё внимание на то что такой проверки вообще не было.

2020-01-31 18:15 UTC, merged