Module4 task1
htmlacademy-nodejs/587797-buy-and-sell-3 pull request #9
Opened 2020-04-10 06:27 UTC by Shv-sergey70

2020-04-14 21:27 UTC, rmuhamedgaliev reviewed
В принципе все неплохо, но необходимо разобраться с файлами `offersRepository.js` и `repository.js`

2020-04-14 21:27 UTC, rmuhamedgaliev commented on src/service/repository.js
> +'use strict';
В чем отличие от файла offersRepository.js ? тут мертвый код.

2020-04-14 21:28 UTC, rmuhamedgaliev requested changes
Удали, пожалуйста, ненужные файлы и нужно решить какой файл брать  `offersRepository.js` или `repository.js`.

2020-04-15 05:52 UTC, Shv-sergey70 commented on src/service/repository.js
> +'use strict';
Да, этот файл был для тестов, забыл удалить

2020-04-15 07:08 UTC, rmuhamedgaliev approved these changes

2020-04-15 07:08 UTC, rmuhamedgaliev commented on src/service/repositories/offersRepository.js
> +    this.offers = JSON.parse(fs.readFileSync(MOCK_FILE_PATH));
Тут только я хочу тебя предупредить, каждый раз когда ты будешь создавать новый инстанс класса OffersRepository то там будет каждый раз новый массив с офферами. Будь осторожен и контролируй это.

2020-04-15 07:08 UTC, merged